create table public.invites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "refId" uuid null default auth.uid (),
  "userId" uuid not null default auth.uid (),
  "refCount" bigint null default '0'::bigint,
  reason character varying null,
  constraint invites_pkey primary key (id, "userId"),
  constraint invites_userId_key unique ("userId"),
  constraint invites_userid_reason_unique unique ("userId", reason),
  constraint invites_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;
