create table public.retweets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  url text null,
  "userId" uuid not null default auth.uid (),
  reason text null,
  constraint retweets_pkey primary key (id),
  constraint retweets_userid_reason_unique unique ("userId", reason),
  constraint retweets_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;

create index IF not exists "retweets_userId_reason_idx" on public.retweets using btree ("userId", reason) TABLESPACE pg_default;
