create table public.topics (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  markets jsonb null,
  meta jsonb null,
  "userId" uuid null default auth.uid (),
  constraint topics_pkey primary key (id),
  constraint topics_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;
