create table public."userMarkets" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "yesMarkets" jsonb[] null,
  "noMarkets" jsonb[] null,
  "userId" uuid not null default auth.uid (),
  "claimedTopicIds" jsonb[] null,
  constraint userMarkets_pkey primary key (id),
  constraint userMarkets_userId_key unique ("userId"),
  constraint userMarkets_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;
