create table public.assets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "userId" uuid null default auth.uid (),
  "pAmount" bigint null,
  constraint assets_pkey primary key (id),
  constraint assets_userId_key unique ("userId"),
  constraint assets_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;
