create table public."assetsLog" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  delta bigint null,
  "userId" uuid not null default auth.uid (),
  reason text null,
  constraint assetsLog_pkey primary key (id),
  constraint assetsLog_userid_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;
